#!/usr/bin/env bash
# Auto-generated by claude_audit.py --comply
# 2026-05-21T04:11:47+00:00
# Project: /tmp/tmp6qryr4re/fake_project
#
# Review every line before running. Each command is idempotent.

set -e

# [HIGH] Track skill untracked-skill in git
# Project-level skills auto-load by directory presence; they should be reviewable.
git -C "/tmp/tmp6qryr4re/fake_project" add ".claude/skills/untracked-skill"

# [HIGH] Track subagent powerful in git
# Subagent definitions affect what tools child sessions can call.
git -C "/tmp/tmp6qryr4re/fake_project" add ".claude/agents/powerful.md"

echo "Done. Run `git status` to review what changed."
