#!/usr/bin/env bash
# Auto-generated by claude_audit.py --comply
# 2026-05-21T04:21:04+00:00
# Project: /Users/sudhiseshachala/projects/narratr-website
#
# Review every line before running. Each command is idempotent.

set -e

# [HIGH] Track skill integration-nextjs-app-router in git
# Project-level skills auto-load by directory presence; they should be reviewable.
git -C "/Users/sudhiseshachala/projects/narratr-website" add ".claude/skills/integration-nextjs-app-router"

echo "Done. Run `git status` to review what changed."
